language: scala
scala:
   - 2.12.4

before_install:
  - cd data
  - wget https://github.com/facebookresearch/fastText/archive/master.zip
  - unzip master.zip
  - cd fastText-master && make && cd ..
  - ./fastText-master/fasttext skipgram -input loremipsum/text.txt -thread 1 -output loremipsum/loremModel -dim 10 -minn 3 -maxn 6
  - cd ..

script:
  - sbt clean coverage test coverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)
