language: scala
scala:
   - 2.12.4

before_install:
  - wget https://github.com/facebookresearch/fastText/archive/master.zip
  - unzip master.zip
  - cd fastText-master && make

script:
  - sbt -jvm-opts travis/jvmopts.compile compile